### ISSUE TITLE
Load data from JSON files to Model objects

### ISSUE THREAD

**Issue by jathurchan** [jathurchan/pokemon-championship#18]
#### Function prototype:
``` c++
template <class ModelType>
ModelType load(std::string fileName)
```
#### `ModelType`:
- Trigger
- Type
- Move
- Creature
- Item
#### Input (JSON files):
- triggersData.json
- typesData.json
- movesData.json
- creaturesData.json
- itemsData.json

**Comment by Gzethicus** [comment]
Merged relevant branch to dev.
